### ISSUE TITLE
Cat count exceeds maximum amount

### ISSUE THREAD

**Issue by bsimser** [TheWizardsCode/Versus#61]
When playtesting found that some blocks held 12/10 cats exceeding the maximum amount of 10.

**Comment by SorraTheOrc** [comment]
This is by design, so I'm removing the bug label, but leaving open in case you have a different suggestion, or a better way of representing it.

What is happening here is the AI is sending cats to high priority blocks. They will keep sending cats until they either decide to lower priority or they gain dominance. Once they have dominance they will start to return to their real homes.

**Comment by SorraTheOrc** [comment]
Perhaps we report it as "x/10 cats live here, y cats are visiting"?

**Comment by SorraTheOrc** [comment]
The update UI indicates how many cats are visiting

**Comment by SorraTheOrc** [comment]
Actually it looks like the AI to move cats out of the block is failing. This is probably because I removed the AI controller ;-)

**Comment by SorraTheOrc** [comment]
Nope, sorry it does work... my cats are breeding and taking over the city!
